import { Suspense, ReactNode } from 'react';
import type { Metadata } from 'next';

import './globals.css';
import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';
import Loading from './loading';

export const metadata: Metadata = {
  title: 'Jinsoul Blog',
  description: 'Generated by Jinsoul',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Suspense fallback={<Loading />}>
          <Header />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
