import { Suspense, ReactNode } from 'react';
import type { Metadata } from 'next';
import { GoogleAnalytics } from '@next/third-parties/google';

import '../styles/globals.css';
import localFont from 'next/font/local';

import Provider from '@/components/provider/Provider';
import Loading from './loading';

const gmarketSans = localFont({
  src: 'fonts/GmarketSansMedium.woff2',
  display: 'swap',
  variable: '--font-gmarketSans',
});

export const metadata: Metadata = {
  title: 'Jinsoul Blog',
  description: 'Generated by Jinsoul',
  robots: { index: false, follow: false },
  verification: {
    google: 'HCBTUIXiE7eXMeGNkwVg8JmmIQsVpvOb6rO6VQ-iUms',
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko" className={`${gmarketSans.variable} font-gmarketSans`}>
      <GoogleAnalytics gaId={'G-4843GGMST8'} />
      <body suppressHydrationWarning={true}>
        <Provider>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </Provider>
      </body>
    </html>
  );
}
